services:
  - type: web
    name: aed-notification-service
    env: docker
    dockerfilePath: service/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: AED_NOTIFY_KEY
        generateValue: true
      - key: AED_NOTIFY_DB
        value: /tmp/notify.db
