services:
  - type: web
    name: aed-notification-service
    runtime: python
    buildCommand: pip install -r service/requirements.txt
    startCommand: python -m uvicorn service.api:app --host 0.0.0.0 --port $PORT
    plan: free
    region: frankfurt # or oregon / ohio / singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: AED_NOTIFY_KEY
        generateValue: true
      - key: AED_NOTIFY_DB
        value: /tmp/notify.db
